"""
Claude Scorer — second-opinion scoring for Premium Hunter picks.

Uses Claude Opus 4.7 to provide independent assessment of each pick.
Returns: claude_score (0-10), claude_tag (SAFE BET/WATCH/SKIP), claude_bullets.

Cost: ~$0.04 per pick. ~10 picks/scan x 9 scans/week ~ $15/month.

Falls back gracefully if API key missing or call fails — never crashes scan.
"""

import os
import json
import time
import sys

try:
    from anthropic import Anthropic
except ImportError:
    Anthropic = None

MODEL = "claude-opus-4-7"  # Opus 4.7 — best judgment

SYSTEM_PROMPT = """You are a balanced second-opinion options analyst reviewing
cash-secured put picks generated by Ash's algorithmic Wheel-strategy scanner.
Your job: provide independent score and flag anything the algo might miss.

Approach: balanced — neither rubber-stamp the algo nor reflexively contrarian.

You assess:
1. Quality of underlying — would a Wheel trader genuinely want to own this?
2. Macro overlay — VIX regime, sector rotation, FOMC/CPI proximity
3. Hidden risk flags — pending M&A, secondary offerings, lawsuits, FDA dates,
   guidance worries, regulatory issues
4. Conviction calibration — does the algo over- or under-rate this?

Return ONLY valid JSON in this exact schema (no preamble, no markdown fences):
{
  "score": <float 0-10>,
  "tag": "SAFE BET" | "WATCH" | "SKIP",
  "bullets": [
    {"tone": "good" | "warn" | "bad", "text": "<one sentence, max 18 words>"}
  ]
}

Rules:
- 2-4 bullets total
- Each bullet <= 18 words, specific, no generic platitudes
- "good" = positive observation; "warn" = caution flag; "bad" = serious concern
- Always include at least one "good" if score >= 6
- Tag rubric: SAFE BET >= 8.0, WATCH 6.0-7.9, SKIP < 6.0
"""


def _build_user_prompt(pick):
    pt = pick.get('put_trade') or {}
    es = pick.get('earnings_stats') or {}
    em = pick.get('expected_move') or {}
    hc = pick.get('hist_chart') or {}

    return f"""Pick: {pick.get('ticker')} ({pick.get('company')})

Sector: {pick.get('sector')}
Market cap: ${(pick.get('market_cap') or 0)/1e9:.1f}B
Current price: ${pick.get('price', 0):.2f}
1y range: ${hc.get('low_1y', 0):.0f}-${hc.get('high_1y', 0):.0f} ({hc.get('pct_1y', 0)}%)

Earnings: {pick.get('next_earnings')} ({pick.get('earnings_weekday')}, {pick.get('earnings_timing')}) - {pick.get('days_to_earnings')} DTE

Trade: Sell ${pt.get('strike')} put, {pt.get('dte')} DTE
Premium: ${pt.get('premium', 0):.2f} ({pt.get('premium_pct', 0):.1f}% of strike)
Delta: {pt.get('delta', 0):.2f}
IV rank: {pick.get('iv_rank')}%

Edge: {pick.get('edge_ratio')}x (expected move {em.get('expected_pct', 0):.1f}% vs avg actual {es.get('avg_move', 0):.1f}%)
Big-move quarters (>5%): {es.get('red_x_count', 0)}/8

Technicals:
- RSI(14): {pick.get('rsi_14')}
- Trend: {pick.get('trend_state')}
- ATRs to strike: {pick.get('atrs_to_strike')}
- 50d MA: ${pick.get('dma_50')}, 200d MA: ${pick.get('dma_200')}
- Beta: {pick.get('beta')}

Auto-signals:
- Insider activity: {pick.get('insider_activity')}
- Buybacks: {pick.get('buybacks')}
- EPS streak: {pick.get('eps_streak')}
- Analyst revisions: {pick.get('analyst_revisions')}
- Short interest: {pick.get('short_interest')}
- Red flags: {pick.get('red_flags')}

Algo score: {pick.get('score')}/10
Algo flags: {pick.get('flags', [])}

Provide your independent JSON assessment."""


def _fallback_result(pick):
    """Used when API unavailable — keeps pipeline running."""
    algo = pick.get('score', 0)
    return {
        'claude_score': algo,
        'claude_tag': 'SAFE BET' if algo >= 8 else 'WATCH' if algo >= 6 else 'SKIP',
        'claude_bullets': [('warn', 'Claude API unavailable - showing algo-derived score only')],
    }


def _score_one(client, pick, retries=2):
    """Score a single pick. Returns dict to merge into pick."""
    user_prompt = _build_user_prompt(pick)

    for attempt in range(retries + 1):
        try:
            resp = client.messages.create(
                model=MODEL,
                max_tokens=600,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_prompt}],
            )
            text = resp.content[0].text.strip()
            text = text.replace("```json", "").replace("```", "").strip()
            data = json.loads(text)

            return {
                'claude_score': float(data.get('score', pick.get('score', 0))),
                'claude_tag': data.get('tag', 'WATCH'),
                'claude_bullets': [
                    (b.get('tone', 'warn'), b.get('text', ''))
                    for b in data.get('bullets', [])
                    if b.get('text')
                ][:4],
            }
        except Exception as e:
            if attempt < retries:
                time.sleep(1.5 ** attempt)
                continue
            print(f"  x Claude API error for {pick.get('ticker')}: {e}",
                  file=sys.stderr, flush=True)
            return _fallback_result(pick)


def score_picks(picks):
    """
    Score all picks. Modifies dicts in-place adding:
      - claude_score (float 0-10)
      - claude_tag (SAFE BET/WATCH/SKIP)
      - claude_bullets (list of (tone, text) tuples)

    Skips silently if ANTHROPIC_API_KEY not set or anthropic not installed.
    """
    api_key = os.environ.get('ANTHROPIC_API_KEY')

    if Anthropic is None:
        print("WARN: anthropic package not installed - skipping Claude scoring", flush=True)
        for pick in picks:
            pick.update(_fallback_result(pick))
        return picks

    if not api_key:
        print("WARN: ANTHROPIC_API_KEY not set - skipping Claude scoring", flush=True)
        for pick in picks:
            pick.update(_fallback_result(pick))
        return picks

    client = Anthropic(api_key=api_key)
    print(f"\nScoring {len(picks)} picks with Claude Opus 4.7...", flush=True)

    for i, pick in enumerate(picks, 1):
        result = _score_one(client, pick)
        pick.update(result)
        print(f"  [{i}/{len(picks)}] {pick.get('ticker'):<6} "
              f"Claude: {result['claude_score']:.1f}  "
              f"Algo: {pick.get('score', 0):.1f}  "
              f"{result['claude_tag']}",
              flush=True)

    return picks
